#!/bin/bash

EXAM_CONTAINER_IP=172.17.0.2
# EXAM_CONTAINER_IP : IP of the exam container
# prospectID : PAM shell USER
prospectID=$USER

logRoot=/$prospectID
logFile=$logRoot/exam.log

[ -d $logRoot ] || mkdir -p $logRoot

ssh \
    -o "StrictHostKeyChecking=no" \
    root@$EXAM_CONTAINER_IP \
    | tee >(ts "%d-%m-%y %H_%M_%S" > $logFile)
